### ISSUE TITLE
Improvement Suggestion: Enhance SDK Behavior for Input Token Limit

### ISSUE THREAD

**Issue by OscarSantosMu** [Fridaplatform/SofttekLLMSDK#3]
# Problem
Currently, when using the Softtek SDK, there is a limitation on the maximum number of input tokens. The system throws an **openai.error.InvalidRequestError** with a message that includes the model's maximum context length and the actual token count in the input. While this is technically informative, it can be improved to enhance the user experience and provide more actionable guidance.

Example:
![image](https://github.com/Fridaplatform/SofttekLLMSDK/assets/38818848/b554974a-c9bc-408d-815a-d3fcecac0c6c)

# Suggested Improvement
We propose enhancing the behavior of the SDK when the input token limit is exceeded to provide more user-friendly and helpful feedback.

1. Auto-Summarization Follow-Up: Instead of just throwing an error, the SDK could automatically make a follow-up call to the API to generate a summarized version of the input within the token limit. This summarized input could be used to generate a response, ensuring that users receive meaningful answers even when their input exceeds the limit.

2. Suggest Truncation or Shortening: Provide users with suggestions on how to reduce the length of their input to fit within the token limit. This could include truncating text or removing less important details.

3. Provide tools to count tokens programmatically.

# Benefits

* Enhanced usability: Users will be more empowered to adjust their queries to fit within the token limit.
* Better context retention: Users can understand which parts of their input were preserved.

<hr>

We encourage feedback and discussions on this proposal to ensure it aligns with user expectations and needs.

> Note from HackMTY 2023 - Ctrl-Alt-Defeat Team:
Comprehensive and clear documentation is crucial for effective utilization of SDKs, ensuring that developers can seamlessly integrate and work with SDK. We kindly urge the responsible teams to consider our suggestion and implement the necessary improvements in the documentation and code.

**Comment by jorgegarcia197** [comment]
Hi @OscarSantosMu just checking your comment and we added a flag in order to check whether the token limit has been reached or not. This is intended this way because as the SDK is able to handle multiple LLM and they handle different token limits.
