### ISSUE TITLE
Filtering prone to mistakes

### ISSUE THREAD

**Issue by AndromedaHelix** [Fridaplatform/SofttekLLMSDK#6]
https://github.com/Fridaplatform/SofttekLLMSDK/blob/0f11c8ed07889b9e13a360509e81b4703e03bc0f/softtek_llm/models.py#L267C3-L267C96

As seen from the development of our project during HackMTY 2023, maybe the way filtering currently works inherently causes several unwanted errors in the structure. 

Our implementation gave a greater freedom to the GPT model, which led us to not have as much issues. I recommend to avoid a yes/no check to verify if the answer is working according to the Filter, as it is not appropriate to deal in absolute terms, especially in LLMs. An alternate solution would be to use a system similar to the temperature to know how related the answer was to the filter's requirements.

**Comment by AndromedaHelix** [comment]
If it helps, [here](https://github.com/JocelynVelarde/HackMty-2023/blob/f504696714a77a3fefb6ea1e7f3d2820c3af2758/frida_connection.py#L58C11-L58C11) is the way we "filtered" the way the model worked

Although not perfect, we did noticed a clear improvement on the results compared to the `Filter` class.

**Comment by jorgegarcia197** [comment]
Hi @AndromedaHelix  I was not able to see the link you provided. Nevertheless we are currently working on the filtering strategy
